# Generated by Django 4.2.15 on 2024-08-22 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0003_aditivar_delete_aditivo_alter_nota_fiscal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivar',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aditivar',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dt. Inclusão'),
            preserve_default=False,
        ),
    ]
