# Generated by Django 3.2.13 on 2022-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0004_alter_obra_cadastrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_empenho',
            name='n_nota',
            field=models.CharField(max_length=300, unique=True, verbose_name='N. da nota de empenho'),
        ),
    ]
