# Generated by Django 4.2.15 on 2024-08-26 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscalizacao', '0004_aditivar_contrato_aditivar_dt_inclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivar',
            name='user_inclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='user_inclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obra',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início'),
        ),
        migrations.CreateModel(
            name='Reajustar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.CharField(max_length=10, verbose_name='Percentual de reajuste')),
                ('valor', models.CharField(max_length=20, verbose_name='Valor do reajuste(R$)')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user_inclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
