# Generated by Django 3.2.12 on 2024-09-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0005_aditivar_user_inclusao_contrato_user_inclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reajustar',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.contrato'),
        ),
    ]
